# DOCKER COMPOSE FILE FOR DEVELOPMENT ONLY
version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/guajojo-backend:cached
    environment:
      DATABASE_URL: postgresql://huascar321:passw0rd@localhost:5432/guajojodb?schema=public
      NODE_ENV: DEVELOPMENT
    command: sleep infinity
    network_mode: service:postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:13.11
    volumes:
      - ../../postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=guajojodb
      - POSTGRES_USER=huascar321
      - POSTGRES_PASSWORD=passw0rd
      - TZ=America/La_Paz
      - PGTZ=America/La_Paz
    restart: unless-stopped